/**
 * Generated by `npm run curated:manifest` (Task 3). This stub holds the six
 * original procedurally-drawn entries widened to the new shape, so the tree
 * typechecks before the real photo set lands in Task 4.
 */
import type { CuratedPhoto } from './curated';

export const CURATED_PHOTOS: CuratedPhoto[] = [
  {
    id: 'aurora-ridge',
    name: 'Aurora Ridge',
    shelf: 'wide-and-calm',
    width: 2400,
    height: 1600,
    file: 'aurora-ridge.jpg',
    licence: {
      name: 'stub',
      attribution: 'stub',
      sourceUrl: 'stub',
    },
    dominant: ['#0b1d3a', '#1f6f6f', '#8fe3c7'],
    difficulty: 'standard',
    recommendedCounts: [50, 100, 150, 200, 250],
  },
  {
    id: 'harbor-grid',
    name: 'Harbor Grid',
    shelf: 'dense-and-busy',
    width: 2400,
    height: 1600,
    file: 'harbor-grid.jpg',
    licence: {
      name: 'stub',
      attribution: 'stub',
      sourceUrl: 'stub',
    },
    dominant: ['#0d1b2a', '#3d6b8c', '#e8c07d'],
    difficulty: 'standard',
    recommendedCounts: [50, 100, 150, 200, 250],
  },
  {
    id: 'canyon-light',
    name: 'Canyon Light',
    shelf: 'one-animal-close',
    width: 1600,
    height: 2400,
    file: 'canyon-light.jpg',
    licence: {
      name: 'stub',
      attribution: 'stub',
      sourceUrl: 'stub',
    },
    dominant: ['#3a1d0b', '#a85c32', '#f2c879'],
    difficulty: 'standard',
    recommendedCounts: [50, 100, 150, 200, 250],
  },
  {
    id: 'orchard-rows',
    name: 'Orchard Rows',
    shelf: 'wide-and-calm',
    width: 2400,
    height: 1800,
    file: 'orchard-rows.jpg',
    licence: {
      name: 'stub',
      attribution: 'stub',
      sourceUrl: 'stub',
    },
    dominant: ['#12240f', '#3f6b2f', '#c7e08f'],
    difficulty: 'standard',
    recommendedCounts: [50, 100, 150, 200, 250],
  },
  {
    id: 'tide-pools',
    name: 'Tide Pools',
    shelf: 'dense-and-busy',
    width: 2400,
    height: 1800,
    file: 'tide-pools.jpg',
    licence: {
      name: 'stub',
      attribution: 'stub',
      sourceUrl: 'stub',
    },
    dominant: ['#001f2b', '#0f6b7a', '#bfe9e6'],
    difficulty: 'standard',
    recommendedCounts: [50, 100, 150, 200, 250],
  },
  {
    id: 'glacier-blue',
    name: 'Glacier Blue',
    shelf: 'one-animal-close',
    width: 2000,
    height: 2000,
    file: 'glacier-blue.jpg',
    licence: {
      name: 'stub',
      attribution: 'stub',
      sourceUrl: 'stub',
    },
    dominant: ['#0a1f33', '#3c7fa8', '#dff3ff'],
    difficulty: 'standard',
    recommendedCounts: [50, 100, 150, 200, 250],
  },
];
